"use strict";
function workflowMailto(data){const subject=`Workflow inquiry from ${data.company}`;const body=`Name: ${data.name}\nCompany: ${data.company}\nEmail: ${data.email}\n\nProcess to fix:\n${data.process}\n\nHow it works today:\n${data.today}`;return `mailto:chainmakerspr@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}
if(typeof module!=="undefined")module.exports={workflowMailto};
if(typeof document!=="undefined"){
 const medreq=document.querySelector('.medreq-visual');
 const permit=document.querySelector('.permit-visual');
 if(medreq)medreq.innerHTML=`<div class="window-bar"><i></i><i></i><i></i><span>medreq / intake</span></div><div class="mr-app"><aside><b>Med<em>Req</em></b><small>Dashboard</small><small class="active">Intake</small><small>Autorizaciones</small><small>Dispatch</small><small>Calendario</small><small>Millaje</small></aside><div class="mr-main"><div class="mr-heading"><span>Intake</span><small>Today · 12 items</small></div><div class="mr-tabs"><b>New referrals <i>08</i></b><span>Needs review <i>03</i></span><span>Complete <i>01</i></span></div><div class="mr-row"><strong>Referral packet</strong><span>Documents received</span><b>Review</b></div><div class="mr-row"><strong>Signed order</strong><span>Authorization attached</span><b>Ready</b></div><div class="mr-row"><strong>Patient intake</strong><span>Missing one field</span><b class="warn">Needs info</b></div></div></div>`;
 if(permit)permit.innerHTML=`<div class="window-bar"><i></i><i></i><i></i><span>permitvault / portfolio</span></div><div class="pv-app"><aside><b>Permit<em>Vault</em></b><small class="active">Overview</small><small>Organizations</small><small>Permits</small><small>Documents</small><small>Renewals</small></aside><div class="pv-main"><div class="pv-heading"><span>Permit portfolio</span><small>3 organizations</small></div><div class="pv-summary"><div><b>18</b><span>Active permits</span></div><div><b>04</b><span>Renewals soon</span></div><div><b>02</b><span>Missing docs</span></div></div><div class="pv-list"><span><i class="green"></i>Business license <b>Active</b></span><span><i class="amber"></i>Health permit <b>Renewal</b></span><span><i class="blue"></i>Fire inspection <b>Documents</b></span></div></div></div>`;
 const form=document.querySelector("#workflow-form");
 document.querySelectorAll("[data-interest]").forEach(link=>link.addEventListener("click",()=>document.querySelector("#contact").scrollIntoView({behavior:"smooth"})));
 form.addEventListener("submit",event=>{event.preventDefault();if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form).entries());window.location.href=workflowMailto(data);document.querySelector("#form-status").textContent="Review the prepared email and send it when you're ready. If it did not open, email chainmakerspr@gmail.com."});
}
